language: node_js
node_js:
  - "lts/*"
before_install:
  # Install peer dependencies
  - "npm install @nestjs/common @nestjs/core postgraphile reflect-metadata"
script:
  - npm run lint
  - npm run test:ci
  - npm run build

after_success:
  - npm pack

deploy:
  provider: npm
  email: hi@alexald.com
  api_key: $NPM_TOKEN
  on:
    tags: true
